---
version: "3"
services:
  mainnetwork:
    ports:
      - 8080:80
      - 5000:5000
  frontend:
    image: eu.gcr.io/akvo-lumen/water-safety-plan/frontend:latest
    command: ["nginx", "-g", "daemon off;"]
  backend:
    image: eu.gcr.io/akvo-lumen/water-safety-plan/backend:latest
    ports:
      - 5000:80
  ci:
    network_mode: service:mainnetwork
    image: alpine:3.14.0
    volumes:
      - ./ci/test:/test:ro
    working_dir: /test
    entrypoint: ./entrypoint.sh
    depends_on:
      - backend
      - frontend
