---
apiVersion: v1
kind: Service
metadata:
  name: water-safety-plan
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    run: water-safety-plan
